//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaVentaMusical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Albumes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Albumes()
        {
            this.Canciones = new HashSet<Canciones>();
        }
    
        public int Id_Album { get; set; }
        public int Id_Artista { get; set; }
        public string Nombre_Album { get; set; }
        public Nullable<int> Ano_Lanzamiento { get; set; }
        public byte[] Imagen_Album { get; set; }
    
        public virtual Artistas Artistas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Canciones> Canciones { get; set; }
    }
}
