//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaVentaMusical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int PagoId { get; set; }
        public int Id_Factura { get; set; }
        public string MetodoPago { get; set; }
        public Nullable<decimal> MontoPagado { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string CodigoAutorizacion { get; set; }
    
        public virtual Facturas Facturas { get; set; }
    }
}
