//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaVentaMusical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjetas
    {
        public int Id_Tarjeta { get; set; }
        public int Id_Usuario { get; set; }
        public int Id_Tipo { get; set; }
        public string Numero_Tarjeta { get; set; }
        public Nullable<System.DateTime> Fecha_Expiracion { get; set; }
        public Nullable<int> CVC { get; set; }
    
        public virtual Tipo_Tarjeta Tipo_Tarjeta { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
